
name: Build and Publish Calendar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run calendar cleaner
        env:
          ICS_URL: ${{ secrets.ICS_URL }}
        run: python calendar_cleaner.py

      - name: Commit and push merged.ics
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add output/merged.ics
          git commit -m 'Update calendar'
          git push
        continue-on-error: true
